# Giới thiệu ngôn ngữ Python

Đầu tiên, hãy đảm bảo rằng chúng ta sử dụng phiên bản Python 3. Không nên sử dụng Python 2 vì nó [sắp bị khai tử](https://pythonclock.org/).

In [1]:
import sys
print(sys.version)

3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0]


## Các kiểu dữ liệu

Python có nhiều kiểu dữ liệu khác nhau. Dưới đây là một số kiểu có sẵn trong Python. Khi các bạn làm việc với các thư viện khác, ta sẽ còn gặp thêm nhiều kiểu dữ liệu nữa.

### Số nguyên

In [2]:
x = 20
print(type(x))

<class 'int'>


### Số thực

In [3]:
x = 17.0
print(type(x))

<class 'float'>


### Số phức

In [4]:
x = 20 + 17j
print(type(x))
print(x)
print(x.real, x.imag)

<type 'complex'>
(20+17j)
(20.0, 17.0)


### Logic

In [1]:
x = True
print(type(x))

True
<type 'bool'>


### Chuỗi

Chuỗi là cấu trúc lưu dữ liệu dạng văn bản (như tin nhắn chẳng hạn). Một chuỗi có thể được gói giữa hai ký tự nháy kép (`"string"`) hoặc nháy đơn (`'string'`). Khi sử dụng nháy kép thì bên trong chuỗi có thể viết dấu nháy đơn dễ dàng hơn.

In [6]:
x = "PiMA 2019 'Deep Learning'"
print(type(x))

<class 'str'>


### Danh sách

In [7]:
x = [1, 2, 3, 4]
print(type(x))

<class 'list'>


Một danh sách có thể bao gồm danh sách khác (nested list), các phần tử của một danh sách có thể thuộc nhiều lớp dữ liệu khác nhau.

In [8]:
x = [[1, 2], [3, 4]] # Ma trận 2x2
x = [[1.0, 2], 3 + 4j, [5, 6]]
print(type(x))

<class 'list'>


### Từ điển

In [9]:
x = {"P": "Project",
     "i": "in",
     "M": "Mathematics",
     "A": "Applications"}
print(type(x))
print(x)

<class 'dict'>
{'P': 'Project', 'i': 'in', 'M': 'Mathematics', 'A': 'Applications'}


### Tuple
Trong Python, khi nhóm các giá trị lại với nhau thành cụm sẽ gọi là `tuple`. Ví dụ như mỗi điểm trong không gian Oxyz được biểu diễn bằng ba giá trị $(x; y; z)$ có thể được biểu diễn dạng tuple.

In [10]:
point = (1, 2, 3)
print(type(point))
x, y, z = point # Lấy ra giá trị từ tuple
print(x, y, z)
y, x = x, y # Hoán đổi giá trị biến bằng tuple
print(x, y)

<class 'tuple'>
1 2 3
2 1


## Ép kiểu

Để "ép" một biến `var` từ kiểu `type1` sang một kiểu dữ liệu khác `type2` có thể làm cú pháp như sau: `type2(var)`

In [11]:
x = 17
y = complex(x)
print(y, type(y))
x = 5.3
y = int(x)
print(y, type(y))

(17+0j) <class 'complex'>
5 <class 'int'>


Tuy nhiên biến kiểu complex không thể chuyển sang float được mà phải được lấy riêng phần thực và phần ảo.

In [12]:
x = 20 + 17j
a = float(x.real)
b = int(x.imag)
print(a, b)

20.0 17


Biến kiểu string, tuple, và hàm `range(begin, end, step)` có thể được ép sang kiểu list.

In [13]:
x = "PiMA"
print(list(x))
print(range(1, 7, 2))
print(list(range(1, 7, 2)))

['P', 'i', 'M', 'A']
range(1, 7, 2)
[1, 3, 5]


In [14]:
print(point)
print(list(point))

(1, 2, 3)
[1, 2, 3]


Và ngược lại:

In [15]:
print(tuple([4,5,6]))

(4, 5, 6)


Các bạn hãy tự thử nghiệm thêm.

## Phép toán

Python hỗ trợ các phép toán `+, -, *, /` (chia lấy kết quả float), `//` (chia lấy phần nguyên, kết quả int), `**` (lên lũy thừa).

Các phép biến đổi bit: `&` (AND), `|` (OR), `^` (XOR).

Đối với biến logic có `and`, `or`, `not`.

Các phép toán so sánh `<` (nhỏ hơn), `>` (lớn hơn), `<=` (nhỏ hơn hoặc bằng), `>=` (lớn hơn hoặc bằng), `==` (bằng)

### Danh sách

Các thao tác cơ bản cho danh sách bao gồm:

- Thêm phần tử vào cuối list (`append`)

In [16]:
x = "Mthemmatic"
x = list(x)
print(x)
x.append('s')
print(x, len(x))

['M', 't', 'h', 'e', 'm', 'm', 'a', 't', 'i', 'c']
['M', 't', 'h', 'e', 'm', 'm', 'a', 't', 'i', 'c', 's'] 11


- Truy cập phần tử

Các phần tử trong list có thể được gọi dựa vào chỉ số (index) hay còn gọi là thứ tự của nó trong danh sách. Trong một list, phần tử đầu tiên có chỉ số là 0.

In [17]:
print(x[0])

M


Một list còn có thể được truy cập thông qua một chỉ số âm. Đối với chỉ số âm, phần tử cuối cùng trong danh sách được đánh số -1, phần tử liền trước có chỉ số nhỏ hơn 1 đơn vị so với phần tử liền sau. Xem ví dụ:

In [18]:
print(x)
print(x[-1])
print(x[-2])

['M', 't', 'h', 'e', 'm', 'm', 'a', 't', 'i', 'c', 's']
s
c


- Chèn phần tử vào một vị trí bất kỳ trong list (`insert`)

In [19]:
x.insert(1, 'a')
print(x)

['M', 'a', 't', 'h', 'e', 'm', 'm', 'a', 't', 'i', 'c', 's']


- Xóa phần tử ở một vị trí bất kỳ (`del`)

In [20]:
del(x[5])
print(x)

['M', 'a', 't', 'h', 'e', 'm', 'a', 't', 'i', 'c', 's']


- Xóa phần tử đầu tiên mang giá trị cho trước (`remove`).

In [21]:
x.remove('a')
print(x)

['M', 't', 'h', 'e', 'm', 'a', 't', 'i', 'c', 's']


- Sắp xếp theo thứ tự tăng dần (`sort`)

In [22]:
x.sort()
print(x)

['M', 'a', 'c', 'e', 'h', 'i', 'm', 's', 't', 't']


- Cắt danh sách (slice) theo cú pháp `[begin : end : step]`.
    - `begin` mặc định là 0, `end` mặc định là độ dài của list, `step` mặc định là 1.
    - Nếu cho `begin` là số âm thì `end` mặc định là 0.
    - Nếu cho `end` là số âm thì `begin` mặc định là `-len(list)`.
    - Nếu cho `step` là số âm thì mặc định `begin = len(list)-1` và `end = 0`.
    - ...

Các bạn có thể thoải mái khám phá thử nghiệm về trò chơi cắt mảng này.

In [23]:
print(x[2:5])
print(x[:5])
print(x[5:])
print(x[::-1])
print(x[-3:])
print(x[:-4])

['c', 'e', 'h']
['M', 'a', 'c', 'e', 'h']
['i', 'm', 's', 't', 't']
['t', 't', 's', 'm', 'i', 'h', 'e', 'c', 'a', 'M']
['s', 't', 't']
['M', 'a', 'c', 'e', 'h', 'i']


### Chuỗi

Chuỗi cũng có thao tác slice giống như list. Ngoài ra chuỗi có các hàm:

- Thay thế một chuỗi con

In [24]:
x = "PiMA 2xxx"
x.replace("xxx", "019")
print(x)
x = x.replace("xxx", "019")
print(x)

PiMA 2xxx
PiMA 2019


- Format chuỗi (đưa các dữ liệu khác vào giữa chuỗi theo kiểu C/C++)

In [25]:
x = "PiMA %d" % (2019) # %d là số nguyên
print(x)
print("Pi = %.2f", 3.1415) # Làm tròn 2 chữ số thập phân
print("{0}, {1}".format("Mathematics", 2019))
print("Math" + "Modelling") # Cộng chuỗi bằng phép tính
print("Math", "Modelling", 2019) # Tự chèn khoảng cách

PiMA 2019
Pi = %.2f 3.1415
Mathematics, 2019
MathModelling
Math Modelling 2019


### Từ điển

Khi gọi một phần tử trong danh sách ta dùng chỉ số của phần tử (e.g. `x[5]`). Tương tự trong từ điển, để tìm một giá trị (value) ta dùng khóa (key). Quan hệ key-value giống với ánh xạ trong toán học. Để thêm một "định nghĩa" mới (một bộ key-value mới) ta có thể thoải mái "gán" (assign) mà không cần qua thao tác nào.

In [26]:
x = {"P": "Project",
     "i": "in",
     "M": "Mathematics",
     "A": "Applications"}
print("M stands for", x["M"])
x["2016"] = "First PiMA camp"
print(x)

M stands for Mathematics
{'P': 'Project', 'i': 'in', 'M': 'Mathematics', 'A': 'Applications', '2016': 'First PiMA camp'}


### Tuple

Có thể truy xuất từng phần tử của tuple qua thứ tự xuất hiện của nó giống như chúng ta làm ở list.

In [27]:
print(point)
print(point[0])

(1, 2, 3)
1


## Vòng lặp và rẽ nhánh
### `for`
Về cơ bản, câu lệnh lặp `for` sẽ có cú pháp `for <object> in <list-alike>`. Trong đó `list-alike` có thể là hàm `items` của một dict, có thể là hàm `range`, hoặc một list, hoặc một chuỗi, etc.

In [28]:
l = [2, 0, 1, 7]
for element in l:
    print(element)

2
0
1
7


In [29]:
for key, value in x.items():
    print(key, "-->", value)

P --> Project
i --> in
M --> Mathematics
A --> Applications
2016 --> First PiMA camp


In [30]:
for i in range(1, 5, 2):
    print(i)

1
3


In [31]:
for i in enumerate(l):
    print(i)

(0, 2)
(1, 0)
(2, 1)
(3, 7)


Ở trên, không có lỗi xảy ra nghĩa là các vòng lặp viết đúng cú pháp. Tuy vậy, để ý rằng tôi có sử dụng lệnh `pass` để bỏ qua nội dung của dòng `for` (tương tự với `while`, `if`, hay bất cứ câu lệnh nào đòi hỏi một đoạn chương trình theo sau).
### `while`
Câu lệnh `while` có cú pháp `while <conditions>: <statements>`. Trong đó `conditions` có thể là một hoặc nhiều điều kiện ghép nhau bằng `and`, `or`, `not`. Ví dụ sau liệt kê các số chính phương nhỏ hơn 10.

In [32]:
i = 1
while (i**2 < 10):
    print(i**2)
    i += 1

1
4
9


### if
Câu lệnh `if` có cú pháp như sau:
```
if <conditions>:
    <statements>
else:
    <statements>
```
Giả sử sau câu lệnh `else:` còn phải xét thêm điều kiện khác nữa thì có thể thay bằng `elif <conditions:`.

In [33]:
x = [1,2]
y = [0,3]
if x > y:
    print("bigger")
elif x < y:
    print("smaller")
elif x == y:
    print("equal")
else:
    pass # ???

bigger


## Hàm (function)
Để khai báo một hàm, dùng cú pháp:

In [34]:
def f(param1, param2=0):
    return param1 + param2 * 0.5

Hàm `f` trên lấy hai tham số, trong đó tham số thứ hai (`param2`) có giá trị mặc định là 0. Lưu ý rằng các tham số có giá trị mặc định phải chuyển ra sau cùng trong danh sách tham số.

In [35]:
def f2(param1=0, param2):
    return param1 + param2*0.5

SyntaxError: non-default argument follows default argument (<ipython-input-35-9ce5ec1e6ed1>, line 1)

Các cách sử dụng hàm sau đây là hợp lệ:

In [38]:
print(f(1))
print(f(1,2))
print(f(param2 = 3, param1 = 2))

1.0
2.0
3.5


Như vậy khi gọi hàm, nếu không ghi rõ tên tham số truyền vào (cách 1, 2) thì các giá trị gán lần lượt cho các tham số theo thứ tự khi khai báo hàm. Nếu có ghi rõ (cách 3) thì không bắt buộc vị trí khai báo.

### `lambda`
Thay vì khai báo hàm `f` bằng cách ghi `def f(x):` có thể dùng phép gán cho những hàm đơn giản chỉ một dòng `return`.

In [39]:
f = lambda param1, param2=0: param1 + param2*0.5
print(f(1))
print(f(1,2))
print(f(param2=3, param1=2))

1.0
2.0
3.5


## Cách tạo nhanh `list`

Một `list` có thể được tạo nhanh thông qua dòng `for`. Chẳng hạn tôi muốn tạo một danh sách các số tự nhiên nhỏ hơn 10.

In [40]:
a = [x for x in range(0,10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Hoặc có thể được tạo nhanh qua hàm `lambda`. Chẳng hạn tôi muốn tạo danh sách gồm bình phương của các số tự nhiên trong khoảng `[4; 8]`:

In [41]:
a = map(lambda x: x**2, range(4, 9)) # trả về con trỏ
print(a) # In ra địa chỉ
print(list(a)) # Ép kiểu danh sách

[16, 25, 36, 49, 64]


## `*` Lớp (`class`)

Class là chức năng quan trọng khiến Python trở thành ngôn ngữ lập trình hướng đối tượng. Mỗi biến trong Python dù lớn hay nhỏ (`int`) đều là một đối tượng (object). Trong một đối tượng chứa các thuộc tính (attribute) đóng vai trò như biến để cung cấp thêm thông tin về đối tượng đó, và các phương pháp (method) đóng vai trò như hàm để thực thi một loạt các lệnh xử lý.

Ví dụ khi mô hình hóa xe cứu thương vào lập trình, có thể biến nó thành một object với kiểu dữ liệu tên `Ambulance` được định nghĩa qua lớp cùng tên. Xe cứu thương có thể bao gồm các thông số như biển số xe (`string`) và vị trí hiện tại của xe (dựa theo mã tỉnh, `int`). Thao tác có thể đặt bên trong đối tượng này là "di chuyển đến" để hỗ trợ một xe cứu thương khác.

In [42]:
class Ambulance:
    def __init__(self, plate, city):
        self.plate = plate
        self.city = city
    def assist(self, another_ambulance):
        self.city = another_ambulance.city
    def __str__(self):
        return "Ambulance {0} is in city {1}"\
                .format(self.plate, self.city)

Lưu ý rằng trong mỗi `class` thường có hàm `__init__` để khởi tạo một đối tượng. Trong ví dụ trên, hàm này có nhận tham số `plate` và gán vào `self.plate`. Có thể hình dung rằng `self.plate` là một biến `plate` là một thuộc tính (hay biến) thuộc lớp Ambulance, còn tham số `plate` được truyền vào hàm `__init__` là một biến độc lập chỉ có giá trị trong hàm này chứ không thuộc lớp `Ambulance`. Hàm `__str__` dùng để hướng dẫn cho câu lệnh `print` nên in ra thông tin gì khi người ta cố gắng in đối tượng này ra màn hình.

Mọi hàm trong class đều phải có tham số `self`. Khi gọi hàm thuộc class không truyền giá trị vào tham số này.

In [43]:
amb1 = Ambulance("65-B1-2019", 32)
amb2 = Ambulance("50-B2-11124", 14)
print(amb1)
print(amb2)
amb2.assist(amb1)
print(amb2)

Ambulance 65-B1-2019 is in city 32
Ambulance 50-B2-11124 is in city 14
Ambulance 50-B2-11124 is in city 32


## Đọc và viết dữ liệu

### Standard I/O

In [44]:
var = int(input("Give me an integer: "))
print(type(var))
print(var)

Give me an integer: 42
<class 'int'>
42


In [45]:
var = input("Give me a value: ")
print(type(var))
print(var)

Give me a value: 28031999
<class 'str'>
28031999


Hàm `input` chỉ có thể đọc trong một dòng mà thôi. Tức là nếu gặp ký tự `'\n'` thì hàm sẽ dừng và trả kết quả cho biến dạng chuỗi.

### File I/O

In [46]:
with open("file_io.dat", "w") as f:
    f.write("Hello")
    f.write("!\n")
    f.write("This is PiMA {0}".format(2019))

Hàm `write` chỉ nhận tham số dạng chuỗi. Để viết các kiểu dữ liệu khác, xem lại phần format chuỗi.

In [47]:
with open("file_io.dat", "r") as f:
    for line in f:
        print(line)

Hello!

This is PiMA 2019


# Giới thiệu về Numpy
NumPy là một thư viện Python được sử dụng nhiều khi làm việc với dữ liệu mảng và các phép toán tuyến tính. Kết hợp với SciPy và Matplotlib, bộ ba thư viện được xem là phiên bản thay thế cho MATLAB. Trong những năm gần đây, Python được xem là một ngôn ngữ tân tiến và đầy đủ hơn MATLAB.

Trong notebook này, chúng ta sẽ tìm hiểu một số kiến thức căn bản trong numpy và cách sử dụng của nó trong các thuật toán tiền xử lý dữ liệu.

In [48]:
import numpy as np 


# Tổng quan về array
Một array trong numpy có kiểu là `numpy.ndarray`. Các yếu tố quan trọng của một `ndarray` bao gồm số chiều (`ndim`), kích thước của mỗi chiều (`shape`), kiểu dữ liệu của từng phần tử (`dtype`). Trong những ví dụ tiếp theo, chúng ta sẽ thấy `ndarray` là một kiểu dữ liệu có tính tùy biến cao, và tại sao chúng ta nên cẩn thận khi làm việc.
## Khởi tạo mảng
### `numpy.array`
Một trong những cách phổ biến để khởi tạo một `ndarray` là từ dữ liệu sẵn có, lưu trong một `list` nào đó, và convert qua kiểu `ndarray` bằng hàm `numpy.array` hoặc `numpy.asarray`.

Hãy thử thay đổi dữ liệu khởi tạo của `a` trong ví dụ dưới đây thành:
- `[[1, 2], [3., 4], [5, 6]]`
- `[[1, 2], [3, 4], 5, 6.]`
- `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`

In [49]:
def show_attributes(a):
    print(a)
    print("The number of dimension is: {0}".format(a.ndim))
    print("The size of each dimension: {0}".format(a.shape))
    print("The type of each element is: {0}".format(a.dtype))


In [50]:
a = np.array([[1, 2], [3., 4], [5, 6]], dtype=int) 
show_attributes(a)


[[1 2]
 [3 4]
 [5 6]]
The number of dimension is: 2
The size of each dimension: (3, 2)
The type of each element is: int64


 Thử xóa parameter `dtype` trong phần khởi tạo của `a` dưới đây:

In [51]:
a = np.array([1, 2, 3, 4, [5, 6]], dtype='object')
show_attributes(a)


[1 2 3 4 list([5, 6])]
The number of dimension is: 1
The size of each dimension: (5,)
The type of each element is: object


Trong trường hợp trên, lỗi xảy ra vì numpy không tự resolve được dimension và dtype của các element trong mảng. Lời khuyên tốt nhất là khi làm việc với numpy nói riêng và Python nói chung, cần kiểm soát kiểu dữ liệu chặt chẽ để tránh gặp lỗi.

**Lưu ý:** Trong tất cả các hàm khởi tạo mảng của numpy đều hỗ trợ một parameter `dtype` để tùy chỉnh kiểu dữ liệu của từng phần tử.

Ngoài cách khởi tạo từ dữ liệu có sẵn, numpy cũng hỗ trợ khởi tạo nhanh dữ liệu qua một số hàm như:
### `numpy.empty`
Khởi tạo một mảng với những số ngẫu nhiên. Bạn cần phải cung cấp shape của mảng dưới dạng một tuple (ví dụ `(2,2)`). Hãy thử thay đổi hoặc xóa parameter `dtype` trong đoạn code dưới đây.

In [52]:
a = np.empty((2,2), dtype=int)
print(a)


[[6917529027641081856 3458773302524708187]
 [6917529027641081858     571738657609842]]


### `numpy.zeros` và `numpy.ones`
Khởi tạo một mảng toàn số 0 hoặc số 1. Bạn cần phải cung cấp shape của mảng dưới dạng một tuple (ví dụ `(2,2)`).

In [53]:
a = np.zeros((2,2))
print(a)
a = np.ones((2, 3), dtype=int)
print(a)


[[ 0.  0.]
 [ 0.  0.]]
[[1 1 1]
 [1 1 1]]


### `numpy.arange`
Khởi tạo một mảng gồm các số trong một interval \[start, stop) cho trước và được giãn cách bởi một giá trị \[step\].

Syntax: `numpy.arange(start, stop, step, ...)`

- Mặc định của `start` là 0
- Mặc định của `step` là 1

In [54]:
a = np.arange(3, 28, 1.5)
print(a)


[  3.    4.5   6.    7.5   9.   10.5  12.   13.5  15.   16.5  18.   19.5
  21.   22.5  24.   25.5  27. ]


### `numpy.linspace`
Khởi tạo một mảng gồm n số trong một interval \[start, stop\] được giãn cách tuyến tính đều nhau

Syntax: `numpy.linspace(start, stop, n, endpoint, ...)`
- Mặc định của `endpoint` là true. Nếu đặt về false, mảng sẽ chỉ bao gồm các số trong interval \[start, stop)
- Mặc định của `n` là 50

In [55]:
a = np.linspace(3, 28, 20)
print(a)


[  3.           4.31578947   5.63157895   6.94736842   8.26315789
   9.57894737  10.89473684  12.21052632  13.52631579  14.84210526
  16.15789474  17.47368421  18.78947368  20.10526316  21.42105263
  22.73684211  24.05263158  25.36842105  26.68421053  28.        ]


### `numpy.logspace`
Khởi tạo một mảng gồm n số trong một interval $[10^{\mathrm{start}}, 10^{\mathrm{stop}}]$, được giãn cách đều nhau theo logarithm cơ số 10.

Syntax: `numpy.logspace(start, stop, n, endpoint, base, ...)`
- Mặc định của `n` là 50.
- Mặc định của `endpoint` là true. Xem thêm ở phần `numpy.linspace`.
- Mặc định của `base` là 10.

Bản chất của hàm này là nó sẽ generate một linspace trước, rồi lấy lũy thừa từng phần tử trong linspace đó theo cơ số `base`.

In [56]:
a = np.linspace(1, 10, 10)
print(a)
a = np.logspace(1, 10, 10, base=2)
print(a)


[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


### `numpy.genfromtxt`
Hàm này thường được dùng để đọc ma trận từ một file text (thường là .csv).

Syntax: `numpy.genfromtxt('filename.csv', delimeter=',')`

## Lọc phần tử (Slicing và Indexing)
Các phần tử trong một `ndarray` có thể được lọc bằng cú pháp `a[obj]`, trong đó `obj` là một tham số đa dạng, quyết định những phần tử nào sẽ được chọn từ `a`, và quyết định format của kết quả lọc
### Basic Slicing
Basic Slicing sẽ được kích hoạt khi `obj` là:
- Một (hoặc tuple) integer
- Một (hoặc tuple) object của lớp `slice`
- Một tuple gồm hỗn hợp integer, object `slice`, `Ellipsis`, hoặc `numpy.newaxis` (hai lớp cuối sẽ không được đề cập)

Basic slicing luôn cho ra kết quả là một _view_. 
 
**`obj` là tuple các integer**
 
Trường hợp đơn giản, mảng một chiều, syntax: `a[i]`. Truy cập phần tử thứ `i` của mảng. Nếu mảng có _n_ chiều, có thể gọi `a[(i_1, i_2, ..., i_n)]` hoặc `a[i_1, i_2, ..., i_n]`.

**`obj` là tuple các object `slice`**

Syntax: `a[slice(start, stop, step)]` hoặc `a[start:stop:step]` (mảng một chiều)

- Mặc định của `start` là 0
- Mặc định của `end` là kích thước của mảng
- Mặc định của `step` là 1

In [57]:
a = np.arange(0, 10, 1)
print(a)
print(a[3:8:2])
s = slice(3,8,2)
print(type(s))
print(a[s])
b = a[s]
print(b)
a[3] = -3
print(b)

[0 1 2 3 4 5 6 7 8 9]
[3 5 7]
<class 'slice'>
[3 5 7]
[3 5 7]
[-3  5  7]


**Lưu ý:** Trong Python, chỉ số của một phần tử trong mảng có thể là số âm. Thông thường, một mảng `a` gồm _n_ phần tử sẽ được đánh số từ 0 tới _n-1_. Ngoài ra, phần tử cuối cùng của mảng cũng được đánh số là -1, và phần tử đầu tiên cũng được đánh số là _-n_. Tổng quát hơn, ta có `a[i] == a[i-n]`, $\forall\ 0\leq i < n$.

Bản chất của `a[slice(start, stop, end)]` có thể _hiểu_ như sau. Chương trình sẽ sinh một `numpy.arange(start, stop, end)`. Sau đó, duyệt qua các chỉ số của `a`, nếu chỉ số đó nằm trong mảng `arange` thì sẽ được thêm vào kết quả. Tuy nhiên, cách tiến hành thực tế trong thư viện không nhất thiết phải như vậy.

Cách hiểu trên sẽ trở nên hữu ích hơn khi chúng ta lọc mảng đa chiều. Ví dụ dưới đây, `a` là mảng hai chiều, được lọc bằng `a[slice(1, 3), slice(1, 4, 2)].` Tức là sẽ có hai mảng arange, `[1, 2]` và `[1, 3]`. Sau đó, chương trình sẽ duyệt qua tất cả các bộ chỉ số `(i,j)` của mảng `a`, nếu $(i, j)\in \{1,2\}\times \{1,3\}$ thì phần tử `a[i,j]` sẽ được thêm vào mảng kết quả.

In [58]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print('a =\n', a)
print('a.shape =', a.shape)
print(a[1::, 1:4:2]) # 1:: means 1:3:1 in this case


a =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a.shape = (3, 4)
[[ 5  7]
 [ 9 11]]


### Advanced Slicing
Advanced slicing sẽ được kích hoạt khi `obj` là:
- Một `ndarray` hoặc `list` với dtype là integer hoặc boolean
- Một tuple, trong đó ít nhất một phần tử của tuple thuộc kiểu sequence, ví dụ: `list`, `tuple`, hoặc `ndarray`

Advanced slicing luôn copy dữ liệu từ mảng gốc sang kết quả.

**`obj` là một `ndarray`**

Giả sử `a` là một `ndarray` với $m$ chiều, $(n_1, n_2, \dots, n_m)$, và `obj` là một `ndarray` với $2\leq k\leq m+1$ chiều, $(n'_1 = m, n'_2, \dots, n'_k)$. Tất cả những phần tử của `obj[i]` ($1\leq i\leq m$) phải là số tự nhiên nhỏ hơn $n_i$. Mảng kết quả sẽ có $k-1$ chiều $(n'_2, n'_3, \dots, n'_k)$.

Thuật toán tìm `a[obj]` có thể hình dung như sau:

- &nbsp;$\forall i := (i_2, i_3, \dots, i_k)$ thỏa mãn $i_j < n'_j$, với $j=2\dots k$.

  - &nbsp;$\texttt{pos}=(\texttt{obj}[1][i], \texttt{obj}[2][i], \dots, \texttt{obj}[m][i])$ là vị trí của phần tử cần tìm
  - Gán `ans[i] = a[pos]`.
<br><br>
- Trả về kết quả `ans`
 
Giả sử ta có một mảng ba chiều ($m=3$) như sau: 

In [59]:
a = np.array([[[0, 1, 2, 3],\
               [4, 5, 6, 7],\
               [8, 9, 10, 11]],\
                   
              [[12, 13, 14, 15],\
               [16, 17, 18, 19],\
               [20, 21, 22, 23]]])
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Shape của mảng trên là (2, 3, 4)
Trong đoạn code dưới đây, thử thay `obj` bằng:
- Một mảng 2 chiều ($k=2$): `[[0], [2], [3]]`, hoặc `[[0, 1], [2, 1], [3, 0]]`
- Một mảng 3 chiều ($k=3$):

```
[[[0, 0, 1],\
 [1, 1, 1]],\

[[1, 1, 0],\
 [2, 1, 0]],\

[[0, 2, 3],\
 [0, 2, 0]]]
```

- Một mảng 4 chiều ($k=4$):

```
[[[[0, 0],\\
  [0, 0]],\\ 
 [[1, 1],
  [1, 1]]],\\

[[[1, 1],\\
  [2, 2]],\\
 [[0, 0],\\
  [1, 1]]],\\

[[[1, 2],\\
  [1, 2]],\\
 [[2, 3],\\
  [2, 3]]]]
```

Dự đoán và kiểm tra kết quả

In [60]:
obj = [[[0, 0, 1],\
 [1, 1, 1]],\

[[1, 1, 0],\
 [2, 1, 0]],\

[[0, 2, 3],\
 [0, 2, 0]]]

print(a[obj])


[[ 4  6 15]
 [20 18 12]]


Trong trường hợp `obj` là một `ndarray` một chiều ($k=1$) gồm các số tự nhiên không quá $m$, gọi `a[obj]` sẽ trả về `a[obj[0]]`, `a[obj[1]]`, v.v..

Chúng ta cũng có thể tiến hành advanced slicing khi `obj` là một `ndarray` với dtype là boolean. Khi đó, `obj` phải có cùng shape với `a`, và khi gọi `a[obj]` ta sẽ nhận được một mảng một chiều chứa các phần tử `a[i]` với `i` là một tuple thỏa mãn `obj[i] == True`.

Ví dụ dưới đây minh họa việc lọc ra các số chia hết cho 6 trong mảng `a`:

In [61]:
obj = (a % 6 == 0)
print(obj)
print(a[obj])


[[[ True False False False]
  [False False  True False]
  [False False False False]]

 [[ True False False False]
  [False False  True False]
  [False False False False]]]
[ 0  6 12 18]


## Duyệt mảng
Duyệt mảng trong Python/Numpy cũng giống như trong C/C++, i.e. ưu tiên hàng trước, cột sau. Hàm `numpy.ndenumerate(a)` trả về danh sách chỉ số của `a` và giá trị tương ứng.

Hàm numpy.reshape sẽ tạo một "khung" array với shape yêu cầu, rồi lần lượt "thả" các phần tử theo thứ tự `ndenumerate` và array mới.

In [62]:
a = np.arange(24).reshape(2,3,4)
print(a)
print('')
for i in np.ndenumerate(a):
    print(i)
print('\n')
a = a.reshape(4,2,3)
print(a)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

((0, 0, 0), 0)
((0, 0, 1), 1)
((0, 0, 2), 2)
((0, 0, 3), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((0, 1, 3), 7)
((0, 2, 0), 8)
((0, 2, 1), 9)
((0, 2, 2), 10)
((0, 2, 3), 11)
((1, 0, 0), 12)
((1, 0, 1), 13)
((1, 0, 2), 14)
((1, 0, 3), 15)
((1, 1, 0), 16)
((1, 1, 1), 17)
((1, 1, 2), 18)
((1, 1, 3), 19)
((1, 2, 0), 20)
((1, 2, 1), 21)
((1, 2, 2), 22)
((1, 2, 3), 23)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


# Tính toán trên array
Cho bài toán sau: Hãy tính tổng các phần tử có trong một mảng. Chúng ta sẽ so sánh hai cách làm giữa việc dùng code Python bình thường và dùng hàm `numpy.sum`.

In [63]:
import time
a = np.arange(100000)


In [64]:
start_time = time.time()
sum = 0
for i in a:
    sum += i
print(sum)
time_taken_1 = time.time()-start_time
print("Time taken: ", time_taken_1)


4999950000
Time taken:  0.06468915939331055


In [65]:
start_time = time.time()
sum = np.sum(a)
print(sum)
time_taken_2 = time.time()-start_time
print("Time taken: ", time_taken_2)
print("numpy.sum is ", time_taken_1/time_taken_2, " times faster.")


4999950000
Time taken:  0.0014362335205078125
numpy.sum is  45.04083665338646  times faster.


## Vectorization
Vectorization là thuật ngữ chỉ việc tận dụng tính chất đồng nhất về kiểu của các phần tử trong mảng để tối ưu hóa các hàm trong Python bằng những ngôn ngữ bậc thấp như C. Có thể hiểu nôm na rằng, khi viết code Python thuần túy, Python luôn phải kiểm tra kiểu dữ liệu của các biến như `sum` và `i` để tìm quy luật `+=` thích hợp. Trong khi đó, `numpy` biết chắc chắn các phần tử trong `a` đều có cùng một kiểu dữ liệu, và nó "đẩy" công việc này xuống cho ngôn ngữ C. C là ngôn ngữ bậc thấp hơn Python, có chú trọng nghiêm ngặt về kiểu dữ liệu hơn Python, và chạy nhanh hơn Python đáng kể. Chính vì vậy những hàm trông đơn giản như `numpy.sum` trong thư viện `numpy` lại có tốc độ rất tối ưu. Thuật ngữ Vectorization được gặp nhiều trong các ngôn ngữ khác như MATLAB và R.

Một hàm `f(x)`, trong đó `x` là một k-tuple, sau khi đã vectorized có thể hoạt động khi `x` là một k-tuple các ndarray với cùng size _n_ nào đó. Khi đó, hàm sẽ áp dụng _n_ lần với _n_ k-tuple, tạo thành bằng cách lấy _k_ phần tử từ các ndarray ra. Kết quả trả về là một ndarray _n_ phần tử.

Trong những mục tiếp theo, chúng ta sẽ tìm hiểu phân loại các hàm đã được vectorized.

### Unary function

Là các hàm chỉ cần một đối số. Các unary functions phổ biến có thể kể đến như: (`numpy.`) `aboslute`, `sqrt`, `sin`, `cos`, `tan`, `log`, `log10`, `log2`, `exp`.

In [66]:
print(np.sqrt(4)) # Works with a number
a = np.array([(i**2) for i in range(0,12,2)])
print(a)
print(np.sqrt(a)) # Also works with an array of numbers


2.0
[  0   4  16  36  64 100]
[  0.   2.   4.   6.   8.  10.]


### Binary function

Là các hàm cần hai đối số. Phổ biến nhất có thể kể đến các phép toán đại số (cộng, trừ, nhân, chia, lũy thừa, chia lấy dư), các phép so sánh (<, >, <=, >=, ==, !=), các phép toán trên bit và boolean (&, |, ^), hàm `numpy.maximum`, hàm `numpy.minimum`.

In [67]:
a = np.array([np.random.randint(0, 20, dtype=int) for _ in range (7)])
b = np.array([np.random.randint(0, 20, dtype=int) for _ in range (7)])
print("a = ", a)
print("b = ", b)
print("a+b = ", a+b)
print("a-b = ", np.subtract(a, b))
print("max(a,b) = ", np.maximum(a, b))


a =  [ 9  4 11  5 19 12 11]
b =  [ 5  7 15  2  6 12  9]
a+b =  [14 11 26  7 25 24 20]
a-b =  [ 4 -3 -4  3 13  0  2]
max(a,b) =  [ 9  7 15  5 19 12 11]


### Sequential function

Là các hàm cần đối số là một dãy số (`ndarray`) và trả về đúng một số. Phổ biến nhất có thể kể đến như (`numpy.`): `mean`, `median`, `var`, `std`, `max`, `min`, `argmax`, `argmin`, `sum`.

Hãy xem lại ví dụ về hàm `numpy.sum` ở trên. Tiếp theo, chúng ta bàn đến việc chọn `axis` trong một sequential function. 

Có thể hình dung rằng, một `ndarray` có _m_ chiều thì sẽ có _m_ trục (axis). Trong một số trường hợp, chúng ta không thích tính tổng của tất cả các phần tử trong một ma trận mà chỉ thích tổng từng cột, ta có thể chỉ định `axis=0`.

In [68]:
a = np.arange(12).reshape(3,4)
print(a)
print(np.sum(a, axis=0))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]


Ta cũng có thể chỉ định nhiều trục mà chúng ta muốn hàm duyệt qua. Ví dụ ta có 3 ma trận và cần tính tổng của từng ma trận, ta đặt `axis=(1,2)`, nếu cần tính tổng của từng hàng của từng ma trận, ta đặt `axis=2`.

In [69]:
a = np.arange(24).reshape(2,3,4)
print(a)
print(np.sum(a, axis=(1,2)))
print(np.sum(a, axis=2))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 66 210]
[[ 6 22 38]
 [54 70 86]]


Numpy thậm chí cũng cung cấp một hàm tên `numpy.vectorize` để giúp vectorize những hàm mà chúng ta tự viết. Tuy nhiên, lại cần lưu ý rằng hàm này thực chất không hề tối ưu thời gian thực thi của hàm chúng ta. Nó không thể transpile code Python của chúng ta sang C được. Mục đích của `numpy.vectorize` là lặp đi lặp lại một hàm trên các phần tử của mảng để cho ra một mảng kết quả.

In [70]:
def factorial(n):
    ans = 1
    for i in range(1, n+1):
        ans *= i
    return ans
vf = np.vectorize(factorial)
print(vf(np.arange(8)))


[   1    1    2    6   24  120  720 5040]


# Một số phương pháp tiền xử lý

Trong phần này chúng ta sẽ xem xét một vài phương pháp xử lý dữ liệu bằng numpy. Lưu ý rằng những phương pháp này cũng được cung cấp sẵn trong thư viện `scikit-learn`.

Trong nhiều phương pháp xử lý dữ liệu, chúng ta thường áp dụng những phép toán như tịnh tiến (cộng/trừ một hằng số với tất cả các điểm dữ liệu) và scaling (nhân/chia một hằng số với tất cả các điểm dữ liệu).

## Feature scaling

Feature scaling hay còn gọi là Min-max normalizing, là phương pháp thu nhỏ vùng dữ liệu lại về khoảng [0, 1] sao cho khoảng cách giữa các điểm dữ liệu vẫn giữ được tỉ lệ.

Một số thuật toán quan tâm đến khoảng cách giữa các điểm dữ liệu (e.g. nearest neighbors, gradient descent), khi khoảng cách lớn quá mức không cần thiết có thể gây ra các bước tính toán cồng kềnh, chậm chạp hơn. Feature scaling tỏ ra hữu ích trong những trường hợp này.

In [71]:
def normalizing(a):
    Min = np.min(a)
    Max = np.max(a)
    a = (a*1.0 - Min) / (Max - Min)
    return a

a = np.random.randint(-28, 3, 99)
print(a)
print(normalizing(a))


[ -5 -25 -11 -15 -24  -4 -10  -9  -7 -26  -7 -24 -14  -9 -10 -22  -1  -9
 -10   0 -14  -1 -15 -12 -24 -12 -20   0   1 -25 -12 -24 -18 -17   1 -25
 -20 -10 -21  -6 -16 -13 -13  -1 -15 -19   2 -13  -2 -22  -9 -26 -11  -8
 -28 -24 -28 -15  -6 -27  -1  -9 -25  -6 -14 -15 -28 -27 -12  -7  -9 -20
 -18   1 -22  -4  -8 -23 -18 -23 -23  -9 -12 -19 -27 -25 -10 -12 -18 -26
 -21 -14 -27 -22 -16   0  -1  -7 -21]
[ 0.76666667  0.1         0.56666667  0.43333333  0.13333333  0.8         0.6
  0.63333333  0.7         0.06666667  0.7         0.13333333  0.46666667
  0.63333333  0.6         0.2         0.9         0.63333333  0.6
  0.93333333  0.46666667  0.9         0.43333333  0.53333333  0.13333333
  0.53333333  0.26666667  0.93333333  0.96666667  0.1         0.53333333
  0.13333333  0.33333333  0.36666667  0.96666667  0.1         0.26666667
  0.6         0.23333333  0.73333333  0.4         0.5         0.5         0.9
  0.43333333  0.3         1.          0.5         0.86666667  0.2
  0.63333333  0.0

## Standardization

Standardization là phương pháp tịnh tiến dữ liệu sao cho giá trị trung bình của nó là 0 và sau đó là chia mỗi điểm dữ liệu cho độ lệch chuẩn của bộ dữ liệu ban đầu.

Chuẩn hóa dữ liệu là một phương pháp hữu ích khi cần so sánh hai bộ dữ liệu có đơn vị đo khác nhau.

In [72]:
def standardizing(a):
    Mean = np.mean(a)
    Std = np.std(a)
    a = (a - Mean) / Std
    return a

b = standardizing(a)
print(b)

[ 1.07877427 -1.26073619  0.37692113 -0.09098096 -1.14376067  1.19574979
  0.49389665  0.61087217  0.84482322 -1.37771171  0.84482322 -1.14376067
  0.02599456  0.61087217  0.49389665 -0.90980962  1.54667636  0.61087217
  0.49389665  1.66365188  0.02599456  1.54667636 -0.09098096  0.25994561
 -1.14376067  0.25994561 -0.67585858  1.66365188  1.7806274  -1.26073619
  0.25994561 -1.14376067 -0.44190753 -0.32493201  1.7806274  -1.26073619
 -0.67585858  0.49389665 -0.7928341   0.96179874 -0.20795648  0.14297008
  0.14297008  1.54667636 -0.09098096 -0.55888305  1.89760293  0.14297008
  1.42970083 -0.90980962  0.61087217 -1.37771171  0.37692113  0.7278477
 -1.61166276 -1.14376067 -1.61166276 -0.09098096  0.96179874 -1.49468724
  1.54667636  0.61087217 -1.26073619  0.96179874  0.02599456 -0.09098096
 -1.61166276 -1.49468724  0.25994561  0.84482322  0.61087217 -0.67585858
 -0.44190753  1.7806274  -0.90980962  1.19574979  0.7278477  -1.02678514
 -0.44190753 -1.02678514 -1.02678514  0.61087217  0.

In [73]:
print(np.mean(b))

-7.5136305707e-17
